# Generated by Django 2.2.11 on 2020-08-31 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
