# Generated by Django 2.2.11 on 2020-09-02 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20200902_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_city',
            field=models.ForeignKey(default=5222, on_delete=django.db.models.deletion.PROTECT, to='cities_light.City'),
            preserve_default=False,
        ),
    ]
