# Generated by Django 2.2.11 on 2020-09-09 04:02

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=common.models.image_upload_path),
        ),
    ]
