# Generated by Django 2.2.11 on 2020-09-12 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.ForeignKey(default=5505, on_delete=django.db.models.deletion.PROTECT, to='cities_light.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='default_city',
            field=models.ForeignKey(default=5505, on_delete=django.db.models.deletion.PROTECT, to='cities_light.City'),
            preserve_default=False,
        ),
    ]
