# Generated by Django 2.2.11 on 2020-09-14 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200912_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.City'),
        ),
    ]
