# Generated by Django 2.2.11 on 2020-09-21 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_profile_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='name',
        ),
    ]
