# Generated by Django 2.2.11 on 2020-09-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20200921_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='default name', max_length=80),
            preserve_default=False,
        ),
    ]
