# Generated by Django 2.2.11 on 2020-10-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('extreme_weather_report', 'Extreme weather report'), ('resilience_project', 'Resilience project'), ('climate_justice_event', 'Climate justice event'), ('well_needed', 'Well needed')], default='extreme_weather_report', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='well_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='well_population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('report_type', 'Extreme weather report type'), ('report_impacts', 'Extreme weather report impacts'), ('other', 'Other')], default='other', max_length=40),
            preserve_default=False,
        ),
    ]
