# Generated by Django 2.2.11 on 2020-10-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20201003_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='well_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='well_population',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('report_type', 'Extreme weather report type'), ('report_impact', 'Extreme weather report impact'), ('project_intention', 'Resilience project intention'), ('other', 'Other')], max_length=40),
        ),
    ]
