# Generated by Django 2.2.11 on 2020-09-09 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file',
        ),
    ]
