# Generated by Django 2.2.11 on 2020-09-12 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_image_order_in_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default_city',
        ),
    ]
