# Generated by Django 2.2.11 on 2020-09-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20200901_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_starter',
            field=models.BooleanField(default=False),
        ),
    ]
