# Generated by Django 2.2.11 on 2020-08-31 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_customcity_customcountry_customregion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customcity',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customcity',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customcity',
            name='region',
        ),
        migrations.DeleteModel(
            name='CustomCountry',
        ),
        migrations.AlterUniqueTogether(
            name='customregion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customregion',
            name='country',
        ),
        migrations.DeleteModel(
            name='CustomCity',
        ),
        migrations.DeleteModel(
            name='CustomRegion',
        ),
    ]
