# Generated by Django 2.2.11 on 2020-08-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_post_default_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='users', to='common.Tag'),
        ),
    ]
