# Generated by Django 2.2.11 on 2020-08-31 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200831_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='default_city',
            new_name='city',
        ),
    ]
