# Generated by Django 2.2.11 on 2020-09-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20200909_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order_in_post',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
